@startuml

skin rose 
actor "Attested \nUser" as AU
box National Directory of Healthcare Providers & Services (NDH)
    collections "Attestation" as AQ
    control "NDH Controller" as NC
    entity "Primary \nSource" as PS
    database "Production" as P
end box
participant "Distributed \nWorkflow Directory" as DWD
|||
AU -> AQ : A Practitioner attest a Relationship \nwith an Organization
AQ -> NC : start NDH validation/verification process

alt Validation failure
hnote over NC
  Validate the attested Resource Instance
  against FHIR StructureDefinition
  if validation fails, notify the Attested User
end note
NC -> AU : Notify the Attested User for the result
else Validation success continue
hnote over NC 
    put the practitioner in attsted queue
end note
|||

end

|||
alt create Relationship Resource Instance
hnote over of NC
    If the Practitioner and Organization resources 
    involved in the relationship are in NDH, 
    but the PractitionerRole resource instance is not in NDH
    then create a new PractitionerRole Resource Instance with:
      1. unique logical id
      2. associate identifier
      3. verification-status = incomplete
      4. create VerificationResult Resource Instance 
      for this PractitionerRole Resource Instance
      5. update the Production
end note
|||
NC -> P : Store the PractitionerRole Resource Instance in the Production
|||
else update Relationship Resource Instance
hnote over of NC
    If the Practitioner and Organization resources 
    involved in the relationship are in NDH, 
    but the PractitionerRole resource instance is in NDH
    then update PractitionerRole Resource Instance with:
      1. verification-status = complete
      2. update VerificationResult Resource Instance 
      for this PractitionerRole Resource Instance
      5. update the Production
end note
|||
NC -> P : Update the PractitionerRole Resource Instance in the Production
end
|||

NC -> AU : Notify the Attested User \nfor the result

P -> DWD : Distribute Workflow Directory \nQuery data from NDH
|||

@enduml
