@startuml
!define PRACTICE_COLOR #B3D9FF
!define ORG_COLOR #FFFFFF
!define ENDPOINT_COLOR #F0F0F0

skinparam defaultFontSize 11
skinparam rectangleFontSize 10
skinparam arrowFontSize 9
skinparam padding 3
skinparam nodesep 80
skinparam ranksep 80

' Top Level - Organizations
rectangle "HISP 1\nOrganization" as HISP1 #LightPink
rectangle "Organization\nAffiliation" as OrgAff #LightCoral
rectangle "Organization\n(Mailing, Billing)" as OrgMain #LightSalmon
' Locations
rectangle "Location 2\n(Practice)" as Loc1 PRACTICE_COLOR
rectangle "Location 3\n(Practice)" as Loc2 PRACTICE_COLOR
'rectangle "Location\n(Practice)" as Loc3 PRACTICE_COLOR
rectangle "Location 4 \n(Practice)" as Loc4 PRACTICE_COLOR

' Practitioner Roles and Practitioner
rectangle "PractitionerRole 1" as PR1 #LightGreen
rectangle "PractitionerRole 2" as PR2 #LightGreen
rectangle "Practitioner" as Prac #Green

' Endpoints
rectangle "Endpoint 1" as EP1 #LightYellow
rectangle "Endpoint 2" as EP2 #LightYellow
rectangle "Endpoint 3" as EP3 #LightYellow
' rectangle "Endpoint 4" as EP4 #LightYellow
rectangle "Endpoint 4" as EP5 #LightYellow
rectangle "Endpoint 5" as EP6 #LightYellow
rectangle "Endpoint 6" as EP7 #LightYellow

' Organizational Structure (Top Level)
HISP1 <-r- OrgAff : <color:red>organization</color>
OrgAff -r-> OrgMain : <color:red>participatingOrganization</color>
' OrgAff -d-> OrgMain : <color:green>managingOrganization</color>

' Organization Affiliation to Endpoints
OrgAff -d-> EP1 : <color:red>endpoint</color>
OrgAff -d-> EP2 : <color:red>endpoint</color>
OrgAff -d-> EP3 : <color:red>endpoint</color>
' OrgAff -d-> EP4 : <color:red>endpoint</color>
OrgAff -d-> EP5 : <color:red>endpoint</color>

' Endpoints to Main Organization
EP1 -r-> OrgMain : <color:green>managingOrganization</color>
EP2 -r-> OrgMain : <color:green>managingOrganization</color>
EP3 -r-> OrgMain : <color:green>managingOrganization</color>
' EP4 -r-> OrgMain : <color:red>managingOrganization</color>
EP5 -r-> OrgMain : <color:green>managingOrganization</color>

' Organization to Locations
OrgMain <-r- Loc1 : <color:blue>ManagingOrganization\nOrganization</color>
OrgMain <-d- Loc2 : <color:blue>ManagingOrganization\nOrganization</color>
' OrgMain -d-> Loc3 : <color:red>Managing\nOrganization</color>
OrgMain <-d- Loc4 : <color:blue>ManagingOrganization\nOrganization</color>

' Locations to PractitionerRoles
Loc1 <-r- PR1 : <color:red>location</color>
Loc2 <-r- PR1 : <color:red>location</color>
Loc4 <-r- PR2 : <color:red>location</color>

' Locations to Endpoints
Loc1 -l-> EP2 : <color:red>endpoint</color>
Loc2 -l-> EP3 : <color:red>endpoint</color>
' Loc3 -l-> EP4 : <color:red>endpoint</color>
Loc4 -l-> EP5 : <color:red>endpoint</color>

' PractitionerRoles to Endpoints
PR1 -d-> EP6 : <color:red>endpoint</color>
PR2 -d-> EP7 : <color:red>endpoint</color>

' PractitionerRoles to Practitioner
PR1 -d-> Prac : <color:red>practitioner</color>
PR2 -d-> Prac : <color:red>practitioner</color>

' PractitionerRoles to Organization
PR1 -u-> OrgMain : <color:red>organization</color>
PR2 -u-> OrgMain : <color:red>organization</color>

' endpoint to managing organization
EP6 -r-> OrgMain : <color:green>managingOrganization</color>
EP7 -r-> OrgMain : <color:green>managingOrganization</color>

@enduml