@startuml

participant "Dr A" as DRA
participant "Dr B" as DRB
participant "Hew Hope EHR is part of Big-Ex\nNot part of Valley Region HIE" as EHR1
participant "Big-Ex Directory" as BigEX
participant "Valley Regional\nHIE XCDR" as HieXCDR
participant "University Hospital\nis part Valley Regional HIE\nXDR" as UhXDR

DRA -> EHR1: Refer Patient to Dr. B at University Hospital
EHR1 -> BigEX: Search for University Hospital
BigEX -> EHR1: Return University Hospital
EHR1 -> BigEX: Search for Dr. B
BigEX -> EHR1: Return Dr. B
Note over EHR1: Need to find Dr. B's endpoint at University Hospital \nPractionerRole has the endpoint
EHR1 -> BigEX: Search for relationship between Dr. B and University Hospital
BigEX -> EHR1: Return PractitionerRole between Dr. B and University Hospital
Note over EHR1: Need Valley Regional HIE Initiator to reach Dr. B
EHR1 -> BigEX: Search HIE Initiator organization
BigEX -> EHR1: Return OrganizationAffiliation between University Hospital and Valley Regional HIE Initiator

EHR1 -> HieXCDR: Transmit Referral HCID=123 intendedRecipient=DrB@universityhealth.org
HieXCDR -> BigEX: Search PractitionerRole with endpoint=DrB@universityhealth.org
BigEX -> HieXCDR: Return PractitionerRole
HieXCDR -> UhXDR: forward message
UhXDR -> DRB: Deliver message
UhXDR -> HieXCDR : Return Delivery Receipt
HieXCDR -> EHR1: Return Delivery Receipt
@enduml