@startuml
skin rose
/'autonumber '/

participant APP as "Local Directory"
box National Directory
participant "Authorization" as AUTH
participant "Schedule\nOperation" as SCHEDULE
participant "NDH Scheduled Export\nRequester" as FHIR
participant "NDH Production\nData" as FILE
end box
|||
autonumber
Group  Setup Account
    APP -> AUTH: Request Account
    AUTH -> AUTH: Evaluate\nRequest
    AUTH -> APP: Receive Account or Denial
end
autonumber stop
|||
autonumber

Group Submit Request from Portal or Application
    APP -> AUTH: Authenticate
    APP -> SCHEDULE: POST [base]/$ndhschExport
    SCHEDULE -> SCHEDULE: Evaluate\nRequest
    SCHEDULE -> APP: 202 Accepted or 4XX Error or 5XX Error
end
autonumber stop
|||
autonumber
loop Based on the schedule NDH execute the operation and save the data to retrieve repository
    SCHEDULE -> FHIR: execute $ndhschExport operation
    FHIR -> FILE: save data to retrieve repository
    hnote over FILE: if keep file set to faluse, delete previous extracted files,\ncreate new files for newly retrieved data
end
autonumber stop
|||
autonumber
loop Retrieve Data via REST API
    APP -> AUTH: Authenticate to Account
    FHIR -> APP: Retrieve List
    FHIR -> APP: Retrieve ndjson files via GET based on the retrieve list   
end
autonumber stop
|||
autonumber
loop Retrieve data via other method (e.g., SFTP)
    APP -> AUTH: Authenticate to Account
    APP -> FILE: Retrieve data via SFTP
end
autonumber stop
|||
autonumber
Group Cancel operation
     APP -> AUTH: Authenticate
    APP -> SCHEDULE: POST [base]/$ndhschExport
    SCHEDULE -> SCHEDULE: Evaluate\nRequest
    SCHEDULE -> APP: 202 Accepted or 4XX Error or 5XX Error
    SCHEDULE -> FHIR: execute $ndhschExport operation to clean up \nsuch as, delete the last extracted files if any
end
autonumber stop
|||
@enduml