@startuml

title National Directory Use Case Actors

Object "GUI for Consumer" as GUI #LightBlue
Object "Coordination Actor" as Coordination #LightGoldenRodYellow
Coordination :  Care coordinator
Coordination :  Benefits coordinator
Coordination :  Refferal coordinator
Coordination :  Discharge planner


Object "Providers and Payers Actor" as Payer2 #LightGoldenRodYellow
Payer2 : Plan Network management (enrollment&contracting)
Payer2 : Plan Claims management
Payer2 : Accountable Care Organization (ACO)
Payer2 : Value based plan
Payer2 : Managed care plan Organization
Payer2 : Credentialing
Payer2 : Compliance/auditing staff
Payer2 : System or Services (Patient attribution service ect.)


Object "Developer Actor" as AppDeveloper #LightGoldenRodYellow
AppDeveloper :  Application developer
AppDeveloper :  EHR developer

Object NationalDirectory #LightSalmon
NationalDirectory : A centralized data hub \nfor healthcare directory information,\noffering accurate and verified data, \nalong with FHIR APIs for accessing the data.
NationalDirectory : Providing a single source of truth for \nhealth plan networks, \nprovider directories, \nand facility directories.\n 
NationalDirectory : Supporting the following use cases:
NationalDirectory : Locating providers, 
NationalDirectory : Comparing health plan networks, 
NationalDirectory : Coordinating facility care,
NationalDirectory : Exchanging health providers information,
NationalDirectory : Reporting public health data.

Object "States HIE/HIN Actor" as States #LightGoldenRodYellow
States : Incorporate regional and national HINs \nto facilitate interoperability


GUI <-left- NationalDirectory
GUI : Consumers to search:
GUI : providers' accessibility information \n(specialty, office hours, taking patients, \nlanguages spoken, etc.) \n 
GUI : relationship between provider \nand insurance plan \n(in-network, out-of-network, etc.) \n 

GUI : facility's accessibility information \n(location, hours, services, etc.)\n 
GUI : community organizations' \naccessibility information \n(location, hours, services, etc.) \n



NationalDirectory -down-> States
NationalDirectory -down-> AppDeveloper
NationalDirectory -up-> Payer2

NationalDirectory -up-> Coordination


@enduml

