@startuml

agent #LightGreen "PractitionerRole:\n\nPractitionerRole/HansSoloRole" as practitionerRole
agent "Practitioner:\n\nPractitioner/HansSolo" as practitioner
agent "Organization:\n\nOrganization/BurrClinic" as organization1
agent "Network:\n\nOrganization/AcmeofCTStdNet" as organization2
agent "Organization:\n\nOrganization/Acme" as organization3
agent "Organization:\n\nOrganization/Hospital" as organization4

agent "Location:\n\nLocation/HospLoc1" as location1
agent "Location:\n\nLocation/HospLoc2" as location2
agent "Location:\n\nLocation/HansSoloClinic" as location3
agent "HealthcareService:\n\nHealthcareService/BurrClinicServices" as healthcareService

practitionerRole -down-> practitioner : "practitioner"
practitionerRole -down-> organization1 : "organization"
practitionerRole -down-> organization2 : "network"
practitionerRole -up-> location2 : "location"
organization2 -left-> organization3: "partOf"

practitionerRole -right-> healthcareService : "healthcareService"
practitionerRole -left-> location3: "location"


healthcareService -right-> location1: "location"
healthcareService -down-> organization1: "providedBy"

location2 -right-> organization4: "managingOrganization"
location1 -up-> organization4: "managingOrganization"

@enduml