@startuml

agent #LightGreen "PractitionerRole:\n\nHansSoloRole" as practitionerRole
agent "Practitioner:\n\nHansSolo" as practitioner

agent "Location:\n\nHansSoloClinic" as location
agent "HealthcareService:\n\nHansSoloService" as healthcareService
agent "InsurancePlan:\n\nBlueCrossBlueShield-CT" as insurancePlan
agent "Network:\n\nBlueCrossBlueShield-CT-PPO" as network
agent "Organization:\n\nBlueCrossBlueShield-CT-ORG" as organization
agent "Endpoint:\n\nHansSoloDirectTrustEndpointReferrals" as directEndpoint
agent "Endpoint:\n\nHansSoloPatientAccessEndpoint" as patientAccessEndpoint

practitionerRole -left-> practitioner : "practitioner"
practitionerRole -right-> healthcareService : "healthcareService"
practitionerRole -down-> network : "network"
practitionerRole -up-> location : "location"
practitionerRole -up-> directEndpoint : "endpoint"
practitionerRole -up-> patientAccessEndpoint : "endpoint"
insurancePlan -up-> network : "network"
network -right-> organization : "partOf"
insurancePlan -up-> organization : "ownedBy"

@enduml