@startuml
hide footbox
title  Discovery Healthcare Providers & Services Information Flow
participant "Inquirer:\n\nOrganization\nIndividual\nor System" as Inquirer #LightBlue
participant "National Directory of\nHealthcare Providers\n& Services" as ndh #LightGreen




Inquirer -> ndh: "Fully qualified query"
ndh -> Inquirer: "Records returned (0..*)"




@enduml