@startuml

agent OrganizationAffiliation as orgAff
agent PractitionerRole as praRole 
agent Practitioner as practitioner 
agent "Organization (payer)" as orgpayer
agent "Organization (employer)" as orgemp
agent "Organization" as organization3
agent Network as network
agent InsurancePlan as insurance
agent "HealthcareService" as healthcare

orgAff -up-> network: "network 0..*"
network -up-> orgpayer: "parterOf 1..1"
insurance -up-> orgpayer: "administeredBy 1..1"
praRole -up-> network: "network 0..*"
praRole -right-> practitioner: "practitioner 0..1"
insurance -left-> network: "network 0..*"
orgemp -down-> insurance: "insuranceplan 0..*"
orgpayer -up-> orgpayer: "parterOf 0..1"
orgemp -up-> orgemp: "parterOf 0..1"
orgAff -up-> organization3: "organization 0..1"
healthcare -up-> network: "network 0..*"


@enduml