@startuml

agent OrganizationAffiliation as orgAff
agent Organization as organization1
agent Organization as organization2
agent Location as location
agent Network as network
agent HealthcareService as service


orgAff -right-> organization2: "partcipating organization 0..1"
orgAff -up-> organization1:  "organization 0..1"
orgAff -down-> service: "healthcare services 0..*"
orgAff -down-> network: "networks 0..*"
orgAff -left-> location: "locations 0..*"

@enduml