@startuml

skinparam defaultTextAlignment center

agent "🏢🏢\nOrganizationAffiliation" as orgAff
agent "🏢\nOrganization\n(Administrating Payer or TPA)" as orgIns2
agent "🏢\nOrganization\n(Obligated Payer)\n(Government\Insco\Employer)" as orgIns1
agent "🏢\nOrganization\n(Healthcare System)" as orgOrgAff
agent "🏥\nOrganization\n(Clinical Org)\n(hospital/clinic/ACO/etc)" as orgOrgPrac
agent "🗺️\nLocation\n(Coverage Area)" as locIns 
agent "📍\nLocation\n(Practice Location)" as locOrgPrac  
agent "Network\n(In-network providers)" as network
agent HealthcareService as service
agent InsurancePlan as insurance
agent "👤🩺\nPractitionerRole" as pracRole
agent "👤\nPractitioner" as practitioner
agent "🧑‍🤝‍🧑\nGroup (Clinician Group)" as group

pracRole -up-> network: "network 0..*"
pracRole -up-> orgOrgPrac: "organization 0..1"
pracRole -up-> service: "healthcareService 0..*"
group -up-> orgOrgPrac: "managingEntity 0..1"
group -down-> practitioner: "member 0..*"
group -down-> pracRole: "member 0..*"
service -left->orgOrgPrac: "providedBy 0..1"
service -left->locOrgPrac: "coverageArea 0..*"
service -right->network: "network 0..*"
pracRole -up-> locOrgPrac: "location 0..*"
orgAff -down-> network: "network 0..*"
orgAff -down-> orgOrgPrac: "organization 0..1"
orgAff -down-> service: "healthcareService 0..*"
orgAff -down-> locOrgPrac: "location 0..*"


orgAff -up-> orgOrgAff: "participatingOrganization 0..1"
insurance -down-> network: "network 0..*"
insurance -up-> locIns: "coverageArea 0..*"
orgOrgPrac -left-> locOrgPrac: "managingOrganization 0..1"
insurance -up-> orgIns2: "administratedBy 1..1"
insurance -down-> orgIns1: "ownedBy 1..1"
network -right-> orgIns1: "partOf 0..1"

pracRole -left-> practitioner: "practitioner 0..1"

locOrgPrac -right-> locOrgPrac : "partOf 0..1"
locIns -right-> locIns : "partOf 0..1"
orgOrgPrac -right-> orgOrgPrac : "partOf 0..1"
orgIns1 -right-> orgIns1 : "partOf 0..1"
orgIns2 -right-> orgIns2 : "partOf 0..1"
orgIns2 -right-> locIns: "managingOrganization 0..1"
orgOrgAff -right-> orgOrgAff : "partOf 0..1"








@enduml