@startuml

agent restriction [
    Restriction Profile
      based on Consent Profile
] 
agent CareTeam as careteam
agent HealthcareService as healthcareService
agent InsurancePlan as insurance
agent Location as location
agent Network as network
agent Organization as organization
agent OrganizationAffiliation as organizationaffiliation
agent Practitioner as practitioner
agent PractitionerRole as practitionerrole


careteam -down-> restriction : "usage-restriction 0..*" 
healthcareService -down-> restriction : "usage-restriction 0..*" 
insurance -down-> restriction : "usage-restriction 0..*" 
location -down-> restriction : "usage-restriction 0..*" 
network -up-> restriction : "usage-restriction 0..*" 
organization -up-> restriction : "usage-restriction 0..*" 
organizationaffiliation -up-> restriction : "usage-restriction 0..*" 
practitioner -up-> restriction : "usage-restriction 0..*" 
practitionerrole -up-> restriction : "usage-restriction 0..*" 

@enduml