@startuml

agent "NetworkPPO" as NetworkPPO
agent "NetworkHMO" as NetworkHMO
agent "OrgManage\nNetwork" as OrgManageNetwork
agent "PractitionerOne\nWithNetwork\nPPOAndHMO" as PractitionerOneWithNetworkPPOAndHMO
agent "PractitionerOne\nNetworkPPORole" as PractitionerOneNetworkPPORole
agent "PractitionerOne\nNetworkHMORole" as PractitionerOneNetworkHMORole


PractitionerOneNetworkPPORole -right-> PractitionerOneWithNetworkPPOAndHMO
PractitionerOneNetworkPPORole -left-> NetworkPPO

PractitionerOneNetworkHMORole -left-> PractitionerOneWithNetworkPPOAndHMO
PractitionerOneNetworkHMORole -right-> NetworkHMO
NetworkPPO -down-> OrgManageNetwork
NetworkHMO -down-> OrgManageNetwork



@enduml