@startuml

agent #LightGreen "HealthcareService\n\nTowson Food" as Service
agent #LightYellow "Organization\n\nSocial\nTowson Food" as Organization
agent #LightYellow "Location\n\nSocial\nTowson Food" as Location

agent #LightGreen "HealthcareService\n\nHope CBO" as Service1
agent #LightYellow "Organization\n\nHope CBO" as Organization1
agent #LightYellow "Location\n\nHope CBO" as Location1


Service -right-> Organization: providedBy
Service -down-> Location: provided at
Location -up-> Organization: managingOrganization

Service1 -right-> Organization1: providedBy
Service1 -down-> Location1: provided at
Location1 -up-> Organization1: managingOrganization



@enduml