@startuml

object "Network" as Network1
Network1 : Network1
object "Network" as Network2
Network2 : Network2

object "Organization" as OrgManageNetwork
OrgManageNetwork : Organization Manage the Network
object "Practitioner" as PractitionerOneWithNetwork1AndNetwork2  #LightGreen
PractitionerOneWithNetwork1AndNetwork2 : Practitioner
PractitionerOneWithNetwork1AndNetwork2 : Paricipating in
PractitionerOneWithNetwork1AndNetwork2 : Both Network1 and Network2 

object "PractitionerRole" as PractitionerOneNetwork1Role #LightYellow
PractitionerOneNetwork1Role : PractitionerRole for
PractitionerOneNetwork1Role : Practitioner and Network1

object "PractitionerRole" as PractitionerOneNetwork2Role #LightYellow
PractitionerOneNetwork2Role : PractitionerRole for
PractitionerOneNetwork2Role : Practitioner and Network2

object "InsurancePlan" as InsurancePlanMedicareAdvantage #LightPink
InsurancePlanMedicareAdvantage : Medicare Advantage

object "InsurancePlan" as InsurancePlanMedicareAdvantageHMO #LightPink
InsurancePlanMedicareAdvantageHMO : Medicare Advantage HMO


PractitionerOneNetwork1Role -right-> PractitionerOneWithNetwork1AndNetwork2
PractitionerOneNetwork1Role -left-> Network1

PractitionerOneNetwork2Role -left-> PractitionerOneWithNetwork1AndNetwork2
PractitionerOneNetwork2Role -right-> Network2
Network1 -down-> OrgManageNetwork : "partOf"
Network2 -down-> OrgManageNetwork : "partOf"

InsurancePlanMedicareAdvantage -down-> Network1
InsurancePlanMedicareAdvantageHMO -down-> Network2


@enduml